
export const traceLabels: { [key: number]: string } = {
    1: "Blocking on Queue Peek",
    2: "Blocking on Queue Receive",
    3: "Blocking on Queue Send",
    4: "Blocking on Stream Buffer Receive",
    5: "Blocking on Stream Buffer Send",
    6: "Create Counting Semaphore",
    7: "Create Counting Semaphore Failed",
    8: "Create Mutex",
    9: "Create Mutex Failed",
    10: "Event Group Clear Bits",
    11: "Event Group Clear Bits from ISR",
    12: "Event Group Create",
    13: "Event Group Create Failed",
    14: "Event Group Delete",
    15: "Event Group Set Bits",
    16: "Event Group Set Bits from ISR",
    17: "Event Group Sync Block",
    18: "Event Group Wait Bits Block",
    19: "Free Memory",
    20: "Give Mutex Recursive",
    21: "Give Mutex Recursive Failed",
    22: "Increase Tick Count",
    23: "Low Power Idle Begin",
    24: "Low Power Idle End",
    25: "Malloc Memory",
    26: "Moved Task to Ready State",
    27: "Pend Function Call",
    28: "Pend Function Call from ISR",
    29: "Post Moved Task to Ready State",
    30: "Queue Create",
    31: "Queue Create Failed",
    32: "Queue Delete",
    33: "Queue Peek",
    34: "Queue Peek Failed",
    35: "Queue Peek from ISR",
    36: "Queue Peek from ISR Failed",
    37: "Queue Registry Add",
    38: "Queue Receive",
    39: "Queue Receive Failed",
    40: "Queue Receive from ISR",
    41: "Queue Receive from ISR Failed",
    42: "Queue Send",
    43: "Queue Send Failed",
    44: "Queue Send from ISR",
    45: "Queue Send from ISR Failed",
    46: "Take Mutex Recursive",
    47: "Take Mutex Recursive Failed",
    48: "Task Create",
    49: "Task Create Failed",
    50: "Task Delay",
    51: "Task Delay Until",
    52: "Task Delete",
    53: "Task Increment Tick",
    54: "Task Notify",
    55: "Task Notify from ISR",
    56: "Task Notify Give from ISR",
    57: "Task Notify Take",
    58: "Task Notify Take Block",
    59: "Task Notify Wait",
    60: "Task Notify Wait Block",
    61: "Task Priority Disinherit",
    62: "Task Priority Inherit",
    63: "Task Priority Set",
    64: "Task Resume",
    65: "Task Resume from ISR",
    66: "Task Suspend",
    67: "Task Switched In",
    68: "Task Switched Out",
    69: "Timer Command Received",
    70: "Timer Command Send",
    71: "Timer Create",
    72: "Timer Create Failed",
    73: "Timer Expired",
    74: "Stream Buffer Create",
    75: "Stream Buffer Create Failed",
    76: "Stream Buffer Create Static Failed",
    77: "Stream Buffer Delete",
    78: "Stream Buffer Receive",
    79: "Stream Buffer Receive Failed",
    80: "Stream Buffer Receive from ISR",
    81: "Stream Buffer Reset",
    82: "Stream Buffer Send",
    83: "Stream Buffer Send Failed",
    84: "Stream Buffer Send from ISR",
};